import { createHash } from 'node:crypto';
import { mkdir, rm, writeFile, readFile, stat } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import type { Readable } from 'node:stream';
import { ulid } from '../lib/ids.js';

export interface StoredObject {
  readonly key: string;
  readonly sizeBytes: number;
  readonly sha256: string;
}

/**
 * Where artifact bytes live.
 *
 * An interface because the disk driver below is the development and
 * single-instance answer, and an object store is the multi-instance one — but
 * nothing above this layer should have to know which it is talking to.
 */
export interface Storage {
  put(bytes: Buffer): Promise<StoredObject>;
  open(key: string): Promise<Readable>;
  size(key: string): Promise<number>;
  delete(key: string): Promise<void>;
}

/**
 * Generates a storage key.
 *
 * A ULID, sharded two levels deep so a directory never holds millions of files.
 * **Nothing derived from user input goes into it.** That is the entirety of the
 * path-traversal defence: there is no filename to sanitize into a path, because
 * the path was never made from a filename.
 */
export function generateStorageKey(): string {
  const id = ulid();
  return `${id.slice(0, 2)}/${id.slice(2, 4)}/${id}`;
}

const KEY_PATTERN = /^[0-9A-HJKMNP-TV-Z]{2}\/[0-9A-HJKMNP-TV-Z]{2}\/[0-9A-HJKMNP-TV-Z]{26}$/;

export function createDiskStorage(rootDir: string): Storage {
  const root = resolve(rootDir);

  /**
   * Resolves a key to an absolute path, refusing anything that lands outside the
   * root.
   *
   * Keys are generated, so this should be unreachable — which is exactly why it
   * is here. A defence that only holds while the thing above it is correct is
   * not a defence, and this one costs a string comparison.
   */
  const pathFor = (key: string): string => {
    if (!KEY_PATTERN.test(key)) {
      throw new Error(`Refusing a storage key that was not generated by this service: ${key}`);
    }
    const target = resolve(join(root, key));
    if (target !== root && !target.startsWith(root + sep)) {
      throw new Error('Refusing a storage key that resolves outside the storage root.');
    }
    return target;
  };

  return {
    async put(bytes) {
      const key = generateStorageKey();
      const target = pathFor(key);
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, bytes, { flag: 'wx' });
      return {
        key,
        sizeBytes: bytes.length,
        sha256: createHash('sha256').update(bytes).digest('hex'),
      };
    },

    async open(key) {
      return createReadStream(pathFor(key));
    },

    async size(key) {
      return (await stat(pathFor(key))).size;
    },

    async delete(key) {
      await rm(pathFor(key), { force: true });
    },
  };
}

/** An in-memory driver, for tests that do not want a temporary directory. */
export function createMemoryStorage(): Storage & { readonly objects: Map<string, Buffer> } {
  const objects = new Map<string, Buffer>();

  return {
    objects,
    async put(bytes) {
      const key = generateStorageKey();
      objects.set(key, Buffer.from(bytes));
      return {
        key,
        sizeBytes: bytes.length,
        sha256: createHash('sha256').update(bytes).digest('hex'),
      };
    },
    async open(key) {
      const bytes = objects.get(key);
      if (bytes === undefined) throw new Error(`No such object: ${key}`);
      const { Readable } = await import('node:stream');
      return Readable.from(bytes);
    },
    async size(key) {
      const bytes = objects.get(key);
      if (bytes === undefined) throw new Error(`No such object: ${key}`);
      return bytes.length;
    },
    async delete(key) {
      objects.delete(key);
    },
  };
}

/** Reads a stored object back into memory. Used by tests and by the checksum audit. */
export async function readObject(storage: Storage, key: string): Promise<Buffer> {
  const chunks: Buffer[] = [];
  const stream = await storage.open(key);
  for await (const chunk of stream) chunks.push(Buffer.from(chunk as Buffer));
  return Buffer.concat(chunks);
}

export { readFile as readLocalFile };
